# Generated by Django 2.2 on 2019-04-17 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='phone')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='名称')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='有效')),
                ('is_admin', models.BooleanField(blank=True, default=False, verbose_name='职员状态')),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='加入日期')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='province')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
