# Generated by Django 2.2 on 2019-04-19 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=100, verbose_name='Phone')),
                ('code', models.CharField(max_length=20, verbose_name='短信验证码')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Send Time')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省'),
        ),
    ]
