# Generated by Django 2.2 on 2019-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190419_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterIndexTogether(
            name='smscode',
            index_together={('phone', 'send_time')},
        ),
    ]
