# Generated by Django 2.2 on 2019-04-24 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190422_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100, verbose_name='ID Number')),
                ('certified_file', models.CharField(max_length=100, verbose_name='Certified File')),
                ('status', models.CharField(choices=[('Verifying', 'Verifying'), ('Pass', 'Pass'), ('Reject', 'Reject')], max_length=20, verbose_name='Status')),
                ('reject_cause', models.TextField(verbose_name='Reject Cause')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(blank=True, choices=[('10', 'grade ten'), ('11', 'grade eleven'), ('12', 'grade twelve'), ('13', 'return students')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('T', 'Teacher'), ('S', 'Student')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Work Place'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterIndexTogether(
            name='smscode',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_admin', 'role'], name='db_customus_is_admi_b7a6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='smscode',
            index=models.Index(fields=['phone', 'send_time'], name='db_smscode_phone_d9ddc9_idx'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
