# Generated by Django 2.2.1 on 2019-05-06 10:11

import db.db_models.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20190424_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(related_name='_customuser_follow_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LocalStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='File Type')),
                ('file', models.FileField(upload_to=db.db_models.storage.file_path, verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
