# Generated by Django 2.2.1 on 2019-05-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20190506_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certified_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.LocalStorage'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='localstorage',
            name='file',
            field=models.FileField(upload_to='storage', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(max_length=20, verbose_name='SMS Code'),
        ),
    ]
