# Generated by Django 2.2.1 on 2019-05-27 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20190522_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('is_pay', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作品提问',
                'verbose_name_plural': '作品提问',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='localstorage',
            options={'verbose_name': '本地存储', 'verbose_name_plural': '本地存储'},
        ),
        migrations.AlterModelOptions(
            name='smscode',
            options={'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
        migrations.AlterField(
            model_name='certification',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='localstorage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='localstorage',
            name='type',
            field=models.CharField(max_length=50, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='localstorage',
            name='watermarked_filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='加水印后的文件名'),
        ),
        migrations.CreateModel(
            name='WorksQuestionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.LocalStorage')),
                ('works_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.WorksQuestion')),
            ],
            options={
                'verbose_name': '作品提问回复',
                'verbose_name_plural': '作品提问回复',
            },
        ),
        migrations.AddField(
            model_name='worksquestion',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorksComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pay', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.LocalStorage')),
            ],
            options={
                'verbose_name': '作品评论',
                'verbose_name_plural': '作品评论',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('summary', models.TextField(blank=True, default='', verbose_name='简介')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='定位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('favorite', models.ManyToManyField(related_name='favorite_works', to=settings.AUTH_USER_MODEL)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.LocalStorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
    ]
