# Generated by Django 2.2.1 on 2019-06-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20190527_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstorage',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='时长'),
        ),
        migrations.AddField(
            model_name='workscomment',
            name='works',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='db.Works'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksquestion',
            name='works',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='db.Works'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='works',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='定位'),
        ),
        migrations.AlterField(
            model_name='works',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型'),
        ),
    ]
