# Generated by Django 2.2.2 on 2019-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190605_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='type',
            field=models.CharField(blank=True, choices=[('Drawing', '素描'), ('Color', '色彩'), ('Sketch', '速写'), ('Constitute', '构成')], max_length=50, null=True, verbose_name='类型'),
        ),
    ]
