# Generated by Django 2.2.2 on 2019-06-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20190612_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.LocalStorage', verbose_name='头像'),
        ),
    ]
