# Generated by Django 2.2.2 on 2019-06-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20190620_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': '用户认证', 'verbose_name_plural': '用户认证'},
        ),
        migrations.AddField(
            model_name='works',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='reject_cause',
            field=models.TextField(blank=True, default='', verbose_name='拒绝原因'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('Verifying', '审核中'), ('Pass', '通过'), ('Reject', '拒绝')], max_length=20, verbose_name='状态'),
        ),
    ]
