# Generated by Django 2.2.2 on 2019-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20190622_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
    ]
