# Generated by Django 2.2.2 on 2019-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_customuser_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
