# Generated by Django 2.2.2 on 2019-07-25 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_works_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=64, verbose_name='支付宝交易号')),
                ('order_no', models.CharField(max_length=64, verbose_name='传入支付宝id')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信支付'), (2, '支付宝支付')], default=1, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='价格')),
                ('trade_status', models.SmallIntegerField(choices=[('WAIT_BUYER_PAY', '交易创建，等待买家付款'), ('TRADE_CLOSED', '在指定时间段内未支付时关闭的交易；在交易完成全额退款成功时关闭的交易。'), ('TRADE_SUCCESS', '交易成功，且可对该交易做操作，如：多级分润、退款等'), ('TRADE_FINISHED', '交易成功且结束，即不可再做任何操作。')], default=1, verbose_name='支付状态')),
                ('pay_item_class', models.CharField(choices=[('WorksComment', '作品评论'), ('WorksQuestion', '作品提问')], max_length=50, verbose_name='所支付类名')),
                ('pay_item_id', models.IntegerField(verbose_name='所支付的id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uodate_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payee', to=settings.AUTH_USER_MODEL, verbose_name='收款方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='付款方')),
            ],
        ),
    ]
