# Generated by Django 2.2.2 on 2019-07-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建，等待买家付款'), ('TRADE_CLOSED', '在指定时间段内未支付时关闭的交易；在交易完成全额退款成功时关闭的交易。'), ('TRADE_SUCCESS', '交易成功，且可对该交易做操作，如：多级分润、退款等'), ('TRADE_FINISHED', '交易成功且结束，即不可再做任何操作。')], default=1, max_length=50, verbose_name='支付状态'),
        ),
    ]
