# Generated by Django 2.2.3 on 2019-08-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20190807_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='push_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='推送时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='class_name',
            field=models.CharField(choices=[('Works', 'Works'), ('WorksQuestion', 'WorksQuestion'), ('CustomUser', 'CustomUser'), ('WorksComment', 'WorksComment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='push_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='推送时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
    ]
