# Generated by Django 2.2.3 on 2019-09-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20190823_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=64, verbose_name='支付宝交易号')),
                ('out_biz_no', models.CharField(max_length=64, verbose_name='商户转账唯一订单号')),
                ('payee_account', models.CharField(max_length=64, verbose_name='支付宝账户')),
                ('payee_type', models.CharField(choices=[('ALIPAY_USERID', '支付宝账号对应的支付宝唯一用户号。以2088开头的16位纯数字组成'), ('ALIPAY_LOGONID', '支付宝登录号，支持邮箱和手机号格式')], default=1, max_length=50, verbose_name='收款方账户类型')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信支付'), (2, '支付宝支付')], default=1, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='转账金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uodate_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_payee', to=settings.AUTH_USER_MODEL, verbose_name='收款方')),
            ],
        ),
    ]
