# Generated by Django 2.2.3 on 2019-09-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_transferinfo_payee_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinfo',
            name='status',
            field=models.CharField(default=None, max_length=50, verbose_name='支付状态'),
        ),
    ]
