# Generated by Django 2.2.3 on 2019-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_transferinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferinfo',
            name='payee_real_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='收款方姓名'),
        ),
    ]
