# Generated by Django 2.2.3 on 2019-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20190918_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferinfo',
            name='payee_real_name',
            field=models.CharField(max_length=64, verbose_name='收款方姓名'),
        ),
    ]
