# Generated by Django 2.2.7 on 2019-12-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_appupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_comment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收听评论')),
                ('listen_reply', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收听回复')),
                ('is_effective', models.BooleanField(default=False, verbose_name='是否生效')),
            ],
            options={
                'verbose_name': '价格设置',
                'verbose_name_plural': '价格设置',
            },
        ),
        migrations.AlterModelOptions(
            name='appupdatelog',
            options={'verbose_name': 'App 更新', 'verbose_name_plural': 'App更新'},
        ),
    ]
