version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/code
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yasuo
  rabbitmq:
    image: rabbitmq:3
    restart: always